name: Build and Push Docker Image

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app-image:latest .          # Build the Docker image from the Dockerfile

      - name: Save Docker image as tar
        run: docker save my-app-image:latest -o my-app-image.tar          # Save the Docker image into a tar file

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app-image.tar


  push:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image         # Load the Docker image from the tar file
        run: docker load -i my-app-image.tar

      - name: Login to DockerHub          # Login to DockerHub using GitHub variables and secrets
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: docker tag my-app-image:latest ${{ vars.DOCKERHUB_USERNAME }}/my-repo:docker_image         # Tag the local Docker image(my-app-image:latest) with DockerHub repository name (docker_image)

      - name: Push image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/my-repo:docker_image     # Push the tagged image to DockerHub