name: Deploy to ECS

on: 
  workflow_dispatch
   
# env:
#   AWS_REGION: ${{ vars.AWS_REGION }}
#   ECR_REPOSITORY: my-app
#   ECS_SERVICE: my-service
#   ECS_CLUSTER: my-cluster
#   ECS_TASK_DEFINITION: task-definition.json
#   CONTAINER_NAME: my-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4          # This authenticates GitHub Actions with AWS services
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Pull image from DockerHub
      - name: Pull DockerHub image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/my-repo:AWS-ECS

      # Tag image for ECR (This allows Docker to push images into ECR)
      - name: Tag image
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/my-repo:AWS-ECS \
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}    # 123456789.dkr.ecr.us-east-1.amazonaws.com/my-app:a1b2c3

      # Push the tagged image to Amazon ECR
      - name: Push image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      # Update ECS task definition with new image (Blueprint for ECS containers)
      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}   

          
      # Deploy the updated task definition to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}    # Updated task definition generated in previous step
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true