name: Build and Push Docker Image

on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/my-repo:YAML .

      - name: Push image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/my-repo:YAML

              