name: Variables and Secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: 
    IMAGE_NAME: 

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      env:
        DOCKER_PASSWORD: s3cur3P@$$w0rd
      run: echi docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publich
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

deploy:
    needs: docker

    runs-on: ubuntu-latest

    steps:
    - name: Docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest